site_name: Daniel Weinhardt
theme:
  name: 'mkdocs'
  search: false
  user_color_mode_toggle: true
  palette:
    primary: teal
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  nav:
    - Home: 'AboutMe.md'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/whyhardt

repo_url: https://github.com/whyhardt
repo_name: Github
